#!/usr/bin/env bash

check_staged() {
  # check if develop.org has been staged for commit
  local input="$1"
  git diff --cached --exit-code "$input" &>/dev/null
  echo $?
}

org2md() {
  local input="$1"
  local output="$2"
  # basic conversion to markdown
  pandoc -f org -t markdown -o "$output" "$input"
  # replace org-agenda markers cleanly
  sed -i 's/\[TODO\]{.*}/**TODO**/g; s/\[DONE\]{.*}/**DONE**/g' "$output"
  # replace startup visibility cleanly
  sed -i '/```{=org}/,/```/d' "$output"
}

main() {
  local input="$1"
  local output="$(sed -e "s/\.org$/\.md/g" <<<"$input")"
  local staged=$(check_staged "$input")
  # update given conditions
  if [ -f "$input" ] && [ "$staged" -eq "1" ]; then
    printf "%s\n" "Syncing develop.md with develop.org"
    org2md "$input" "$output"
    git add "$input"
  fi
}

# execute overall workflow
source="./docs/develop.org"
main "$source"
