#!/usr/bin/env bash
# Pre-commit hook for converting development log from org to markdown

check_staged() {
  # check if develop.org has been staged for commit
  local input="$1"
  git diff --cached --exit-code "$input" &>/dev/null
  echo $?
}

org2md() {
  local input="$1"
  local output="$(sed -e 's/\.org$/\.md/g' <<<"$input")"
  local staged=$(check_staged "$input")
  # update given conditions
  if [ -f "$input" ] && [ "$staged" -eq "1" ]; then
    printf "%s\n" "Syncing develop.md with develop.org"
    # basic conversion to markdown
    pandoc -f org -t markdown -o "$output" "$input"
    # add TOC to markdown
    pandoc -s -t markdown --toc -o "$output" "$output"
    # add TOC title
    sed -i '1s/^/Table of Contents/' "$output"
    # replace org-agenda markers cleanly
    sed -i 's/\[TODO\]{.*}/**TODO**/g; s/\[DONE\]{.*}/**DONE**/g' "$output"
    # replace startup visibility cleanly
    sed -i '/```{=org}/,/```/d' "$output"
    # stage new markdown for commit
    git add "$output"
  fi
}

main() {
  # execute overall workflow
  local develop_org="$1"
  org2md "$develop_org"
}

develop_org="./docs/develop.org"
main "$develop_org"
